# Rotas do LocalAccommodationBundle
local_demo_dashboard:
  path: /local-accommodation/dashboard
  controller: LocalAccommodationBundle\Controller\DashboardController::index

local_accommodation_guests:
  path: /local-accommodation/guests
  controller: LocalAccommodationBundle\Controller\GuestController::index
