# Rotas do LocalAccommodationBundle
local_demo_dashboard:
  path: /local-accommodation/dashboard
  controller: LocalAccommodationBundle\Controller\DashboardController::index

local_demo_hospedes:
  path: /local-accommodation/hospedes
  controller: LocalAccommodationBundle\Controller\HospedeController::index
